module.exports = {
	NAME: '[NAME]'
	, DB_HOST: '[DB_HOST]'
	, DB_PORT: '[DB_PORT]'
	, DB_NAME: '[DB_NAME]'
	, SESSION_SECRET: '[SESSION_SECRET]'
	, APP_PORT: '[APP_PORT]'
	, DEFAULT_PASS: '[DEFAULT_PASS]'
	, ADMIN: {
		NAME: '[ADMIN_NAME]'
		, EMAIL: '[ADMIN_EMAIL]'
		, PASS: '[ADMIN_PASSWORD]'
		, SITE: '[YOUR_SITE]'
	}
	, DEFAULT_AVATAR: '[USER_AVATAT_DEFAULT]'

	, RCODES: {
		SUCCESS: 0
		, PARAM_MISSING: 10001
		, PARAM_ILLEGAL: 10002
		, DB_ERROR: 10003
	}
}